[package]
name = "rainbow_trick"
version = "0.1.0"
authors = ["Will McGloughlin <willem.mcg@gmail.com>"]
edition = "2021"
license = "MIT"

[lib]
crate-type = ["cdylib"]

[dependencies]
extism-pdk = "0.3.4"
lazy_static = "1.4.0"
colorsys = "0.6.7"